FROM {{ image }}

MAINTAINER Rob McQueen

# Install Python on Ubuntu
#RUN apt-get update && apt-get install -y \
#  build-essential \
#  python-dev \
#  python-virtualenv \
#  sudo \
#  libffi-dev

# Install Python on Centos
RUN yum install -y wget
RUN wget http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-8.noarch.rpm
RUN rpm -ivh epel-release-7-8.noarch.rpm
RUN yum install -y python-pip
RUN pip install --upgrade pip
RUN pip install virtualenv

# Install Ansible
RUN mkdir /opt/ansible && virtualenv /opt/ansible/venv && \
  /opt/ansible/venv/bin/pip install ansible

ADD . /build
COPY .ansible-test /build
WORKDIR /build

CMD /opt/ansible/venv/bin/ansible-playbook -i inventory.yml \
    -c local -s -e testing=true -e role=$DOCKER_TEST_ROLE \
    {{ extra_args| join(" ") }} playbook.yml; /bin/bash
