FROM {{ image }}

MAINTAINER Rob McQueen

# Install Python on Ubuntu
RUN apt-get update && apt-get install -y \
  build-essential \
  python-dev \
  python-virtualenv \
  sudo \
  libffi-dev

# Install Python on Centos
RUN yum install python-pip
RUN pip install virtualenv

# Install Ansible
RUN mkdir /opt/ansible && virtualenv /opt/ansible/venv && \
  /opt/ansible/venv/bin/pip install ansible

ADD . /build
COPY .ansible-test /build
WORKDIR /build

CMD /opt/ansible/venv/bin/ansible-playbook -i inventory.yml \
    -c local -s -e testing=true -e role=$DOCKER_TEST_ROLE \
    {{ extra_args| join(" ") }} playbook.yml; /bin/bash
